"""Add is_primary to tags

Revision ID: 1c26600bb2cd
Revises: 7440cacf3532
Create Date: 2025-03-24 22:21:38.927027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c26600bb2cd'
down_revision: Union[str, None] = '7440cacf3532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('is_primary', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'is_primary')
    # ### end Alembic commands ###
