"""Add price to advertisements

Revision ID: 7440cacf3532
Revises: 418fe4b4ed3d
Create Date: 2025-03-24 16:55:41.195275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7440cacf3532'
down_revision: Union[str, None] = '418fe4b4ed3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('price', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'price')
    # ### end Alembic commands ###
